[package]
name = "rust-echo-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "^0.3.17"
anyhow = "1.0.42"
structopt = "0.3.22"

[profile.release]
lto = true

